//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSGC_PUC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClienteAluno
    {
        public int IdCliente { get; set; }
        public int CPF { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> Telefone { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }

        //Robson Souza.
        //Retorna a lista de todos os alunos cadastrados.
        public List<ClienteAluno> getAllClienteAluno(Entities1 entities1)
        {
            try
            {
                if (entities1 != null)
                {
                    return entities1.ClienteAluno.ToList();
                }
                return null;
            }
            catch (Exception)
            {
                throw;
            }
        }

        //Robson Souza.
        //Valida se as credenciais fornecidas estão corretas.
        //Retorna um Json com a chave "resultado" igual a TRUE se as credenciais estão corretas ou FALSE para incorretas.
        public bool getValidateCredencials(Entities1 entities1, string usuario, string senha)
        {
            try
            {
                if (entities1 != null)
                {
                    var result = entities1.ClienteAluno.ToList().Find(e => e.Email.ToLower().Equals(usuario) && e.Senha.Equals(senha));

                    return result==null?false:true;
                }
                return false;
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}
